Story_6/urls.py
from django.urls import path
from . import views

app_name = 'Story_6'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<pk>', views.delete_status, name="delete"),
   
    # dilanjutkan ...
]

storyEnam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('Story_6.urls')),
	path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('admin/', admin.site.urls),
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.story7, name='story7'),
    
    # dilanjutkan ...
]

story_8/urls.py
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.story8, name='story8'),
    
    # dilanjutkan ...
]

Story_6/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Status(models.Model):
	status = models.CharField(max_length=300, blank=False, null=False)
	date = models.DateTimeField(auto_now_add=True)

story_7/models.py
from django.db import models

# Create your models here.

story_8/models.py
from django.db import models

# Create your models here.

story_9/models.py
from django.db import models

# Create your models here.

Story_6/forms.py
from django import forms
from .models import Status
from django.forms import widgets
from django.utils import timezone
import datetime

class statusForm(forms.Form):
	status = forms.CharField(widget = forms.TextInput(attrs={"id":"status"}))

Story_6/views.py
from django.shortcuts import render, redirect
from .forms import statusForm
from .models import Status
import datetime

# Create your views here.
def index(request):
	if request.method == 'POST':
		form = statusForm(request.POST)
		if form.is_valid():
			status = form.cleaned_data['status']
			Status.objects.create(status=status)
			return redirect('Story_6:index')
	else :
		form = statusForm()
		hasil = Status.objects.all()
	return render(request, 'index.html', {'statusForm' : form, 'status':hasil})

def delete_status(request, pk):
	delete_status = Status.objects.get(pk=pk)
	delete_status.delete()
	return redirect('Story_6:index')

story_7/views.py
from django.shortcuts import render

# Create your views here.
def story7(request):
    return render(request, 'story7.html')

story_8/views.py
from django.shortcuts import render

# Create your views here.
def story8(request):
    return render(request, 'story8.html')

story_9/views.py
from django.shortcuts import render

# Create your views here.

Story_6/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
	<div id="navbar">
<nav class="navbar navbar-expand-lg  navbar-dark" style="background-color: #67B8A5;">
  <a class="navbar-brand" href="">Felicia Honggo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</nav>
</div>
{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>
</html>

Story_6/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<head>
</head>

<body>


<h1 style="text-align: center;">
  Halo, Apa Kabarr?
</h1>

<br>
<br>

 <br>
    <div id="title" style="text-align: center;">
      <h4>Status Form</h4>
      <form method='POST'> 
        {% csrf_token %}
        {{ statusForm.status }}
        <button id='submit' type='submit' class="save">Save</button>
      </form>
    </div>


  
    <br>
    <br>
    <div id="title2" style="text-align: center;">
      <h4>Status</h4>
    </div>
    <div class="container">
      <!--bikin table-->
      <table style="width:100%; text-align: center;">
  <tr>
    <th style="width: 30%">Status</th>
    <th>Waktu</th>
    <th> </th>
  </tr>
   {% for form_output in status %}
      <div class="row">
        <tr>
        <div class="col-sm-6">
         <td style="max-width: 30%; word-break: break-word;"> {{ form_output.status }} </td>
        </div>
        <div class="col-sm-3">
         <td> {{ form_output.date }} </td>
        </div>
        <div class="col-sm-3">
         <td> <a href= "{% url 'Story_6:delete' pk=form_output.pk %} "> <button type="submit">Hapus</button></a> </td>
        </div>
      </tr>
      </div>

      
    {% endfor %}
  </table>
    </div>
    </body>
<br>
<br>
<br>


{% endblock %}

story_8/templates/story8.html
{% extends "story8base.html" %}
{% load static %}

  {% block content %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Library</title>

    <div class="text-center container mt-5">
        <h1>Book List</h1>
      
        <div class="container mt-5">
              <input id="myInput" class="form-control" type="search" placeholder="Search for your book here!">
          <br>
          <input type="submit" id="button" value="search">
        </div>
        <div class="table-responsive mt-5">
            <table class=" table table-light table-hover">
                <thead class = "thead">
                <tr class="text-center">
                    <th scope="col" class="align-middle">No</th>
                    <th scope="col" class="cover">Cover</th>
                    <th scope="col" class="title">Title</th>
                    <th scope="col" class="categories">Description</th> 
                    <th scope="col" class="author">Authors</th>
                    <th scope="col" class="publisher">Publisher</th>
                   
                  </tr>
              </thead>
              <tbody></tbody>
            </table>
        </div>
      
      </div>
      
      



  {% endblock %}

story_8/templates/story8base.html
{% load static %}
<!DOCTYPE html>
<html>


<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="{% static 'story8.js' %}"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
</head>

<body class="night">
	<div id="navbar">
<nav class="navbar navbar-expand-lg  navbar-dark" style="background-color: #67B8A5;">
  <a class="navbar-brand" href="">Felicia Honggo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</nav>
</div>



{% block content %}
{% endblock %}



</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- <link rel="stylesheet" type="text/css" href="story7.css"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'story7.css' %}">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="{% static 'story7.js' %}"></script>


</head>
<body class="night">
	<div id="navbar">
<nav class="navbar navbar-expand-lg  navbar-dark" style="background-color: #67B8A5;">
  <a class="navbar-brand" href="">Felicia Honggo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</nav>
</div>


<!-- <div class="toggle"> </div>
<div class="content">
	aaaaaaaaaaaaaaaaaaaa
</div> -->
{% block content %}
{% endblock %}



</body>
</html>

templates/story7.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br>
<br>
<h1 style="text-align: center;">
  Halo, Apa Kabarr?
<br>
<br>

 <label class="switch">
 	<input class ="toggle" type="checkbox">
  	<span class="slider"></span>
</label>


<div id="accordions">
  	<button class ="accordion">
     	<h3>Aktivitas</h3> 
     	<img src="{% static 'arrow-down-icon-png-3.png' %}" style="max-width:40px;float:right;">
  	</button>
 	<div class="panel">
    	<p>
	    Belajar
	    Kuliah
	    Nugas
	    Tidur
	    Repeat :)
	    </p>
  	</div>

  	<button class="accordion"> 
  		<h3 style="text-align: left;">Pengalaman Organisasi dan Kepanitiaan</h3>
  		<img src="{% static 'arrow-down-icon-png-3.png' %}" style="max-width:40px;float:right;">
 	</button> 
  	<div class="panel">
    	<p>
    	Organisasi
    	</p>
    		<ul>
		      	<li>Kestari DPM Fasilkom UI</li>
		      	<li>Staff Creative Events KMBUI</li>
    		</ul>
        <p>
    	Kepanitiaan
    	</p>
   		<ul>
		      <li>Sekretaris BETIS 2020</li>
		      <li>Staff Acara Wisgan</li>
		      <li>Staff LO Wisgen</li>
		      <li>Staff Bazkom CGT</li>
		      <li>Staff Sponsorship COMPFEST 11</li>
		      <li>Staff Acara Makrab KMBUI 2018</li>
    	</ul>
  	</div>
  	<button class="accordion"> 
   		<h3>Prestasi</h3>
   		<img src="{% static 'arrow-down-icon-png-3.png' %}" style="max-width:40px;float:right;">
 	</button>
  	<div class="panel">
    <p>
      Belom ada nih, sad...
    </p>

  	</div>

</div>
 

<br>
<br>
<br>


{% endblock %}